/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WebRtcConnectionsService } from "../webRtcConnections.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WebRtcConnectionsCreateInput } from "./WebRtcConnectionsCreateInput";
import { WebRtcConnections } from "./WebRtcConnections";
import { WebRtcConnectionsFindManyArgs } from "./WebRtcConnectionsFindManyArgs";
import { WebRtcConnectionsWhereUniqueInput } from "./WebRtcConnectionsWhereUniqueInput";
import { WebRtcConnectionsUpdateInput } from "./WebRtcConnectionsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WebRtcConnectionsControllerBase {
  constructor(
    protected readonly service: WebRtcConnectionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WebRtcConnections })
  @nestAccessControl.UseRoles({
    resource: "WebRtcConnections",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWebRtcConnections(
    @common.Body() data: WebRtcConnectionsCreateInput
  ): Promise<WebRtcConnections> {
    return await this.service.createWebRtcConnections({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        chatSession: data.chatSession
          ? {
              connect: data.chatSession,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        connectionId: true,

        user: {
          select: {
            id: true,
          },
        },

        chatSession: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WebRtcConnections] })
  @ApiNestedQuery(WebRtcConnectionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WebRtcConnections",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async webRtcConnectionsItems(
    @common.Req() request: Request
  ): Promise<WebRtcConnections[]> {
    const args = plainToClass(WebRtcConnectionsFindManyArgs, request.query);
    return this.service.webRtcConnectionsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        connectionId: true,

        user: {
          select: {
            id: true,
          },
        },

        chatSession: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WebRtcConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebRtcConnections",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async webRtcConnections(
    @common.Param() params: WebRtcConnectionsWhereUniqueInput
  ): Promise<WebRtcConnections | null> {
    const result = await this.service.webRtcConnections({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        connectionId: true,

        user: {
          select: {
            id: true,
          },
        },

        chatSession: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WebRtcConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebRtcConnections",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWebRtcConnections(
    @common.Param() params: WebRtcConnectionsWhereUniqueInput,
    @common.Body() data: WebRtcConnectionsUpdateInput
  ): Promise<WebRtcConnections | null> {
    try {
      return await this.service.updateWebRtcConnections({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          chatSession: data.chatSession
            ? {
                connect: data.chatSession,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isActive: true,
          connectionId: true,

          user: {
            select: {
              id: true,
            },
          },

          chatSession: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WebRtcConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WebRtcConnections",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWebRtcConnections(
    @common.Param() params: WebRtcConnectionsWhereUniqueInput
  ): Promise<WebRtcConnections | null> {
    try {
      return await this.service.deleteWebRtcConnections({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isActive: true,
          connectionId: true,

          user: {
            select: {
              id: true,
            },
          },

          chatSession: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/webrtc-connections")
  @swagger.ApiOkResponse({
    type: WebRtcConnectionsCreateInput,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateWebRtcConnection(
    @common.Body()
    body: WebRtcConnectionsFindManyArgs
  ): Promise<WebRtcConnectionsCreateInput> {
    return this.service.CreateWebRtcConnection(body);
  }

  @common.Get("/webrtc-connections")
  @swagger.ApiOkResponse({
    type: WebRtcConnectionsFindManyArgs,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetAllWebRtcConnections(
    @common.Body()
    body: WebRtcConnectionsFindManyArgs
  ): Promise<WebRtcConnectionsFindManyArgs[]> {
    return this.service.GetAllWebRtcConnections(body);
  }
}
