/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Signal } from "./Signal";
import { SignalCountArgs } from "./SignalCountArgs";
import { SignalFindManyArgs } from "./SignalFindManyArgs";
import { SignalFindUniqueArgs } from "./SignalFindUniqueArgs";
import { CreateSignalArgs } from "./CreateSignalArgs";
import { UpdateSignalArgs } from "./UpdateSignalArgs";
import { DeleteSignalArgs } from "./DeleteSignalArgs";
import { SignalCreateInput } from "./SignalCreateInput";
import { SignalService } from "../signal.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Signal)
export class SignalResolverBase {
  constructor(
    protected readonly service: SignalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "read",
    possession: "any",
  })
  async _signalsMeta(
    @graphql.Args() args: SignalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Signal])
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "read",
    possession: "any",
  })
  async signals(@graphql.Args() args: SignalFindManyArgs): Promise<Signal[]> {
    return this.service.signals(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Signal, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "read",
    possession: "own",
  })
  async signal(
    @graphql.Args() args: SignalFindUniqueArgs
  ): Promise<Signal | null> {
    const result = await this.service.signal(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Signal)
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "create",
    possession: "any",
  })
  async createSignal(@graphql.Args() args: CreateSignalArgs): Promise<Signal> {
    return await this.service.createSignal({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Signal)
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "update",
    possession: "any",
  })
  async updateSignal(
    @graphql.Args() args: UpdateSignalArgs
  ): Promise<Signal | null> {
    try {
      return await this.service.updateSignal({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Signal)
  @nestAccessControl.UseRoles({
    resource: "Signal",
    action: "delete",
    possession: "any",
  })
  async deleteSignal(
    @graphql.Args() args: DeleteSignalArgs
  ): Promise<Signal | null> {
    try {
      return await this.service.deleteSignal(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SignalCreateInput)
  async CreateSignalPost(
    @graphql.Args()
    args: SignalCreateInput
  ): Promise<SignalCreateInput> {
    return this.service.CreateSignalPost(args);
  }

  @graphql.Query(() => [SignalCreateInput])
  async GetSignals(
    @graphql.Args()
    args: SignalCreateInput
  ): Promise<SignalCreateInput[]> {
    return this.service.GetSignals(args);
  }
}
